name = "AstroDynamics"
uuid = "26b2238e-ca90-4cf4-8490-3e94fe8d108e"
authors = ["Isaac Velasco"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
